<?php namespace Spiroski\Domain\Events\Bundle;

use Psr\Log\LoggerInterface;
use Spiroski\Domain\Events\BasicDispatcher;

class DebugDispatcher extends BasicDispatcher
{
    /**
     * @var LoggerInterface
     */
    protected $logger;

    /**
     * DebugDispatcher constructor.
     * @param LoggerInterface $logger
     */
    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
        parent::__construct();
    }

    public function dispatch(array $events)
    {
        foreach ($events as $event) {
            $this->logger->debug("Dispatching event {event}", ['event' => get_class($event)]);
        }

        parent::dispatch($events); // TODO: Change the autogenerated stub
    }


}