<?php namespace Spiroski\Domain\Events\Bundle;

use Spiroski\Domain\Events\Listener;
use Spiroski\Domain\Events\Subscriber;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class SpiroskiDomainEventsBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        $container
            ->registerForAutoconfiguration(Subscriber::class)
            ->addTag('spiroski_domain_events.subscriber');
        $container
            ->registerForAutoconfiguration(Listener::class)
            ->addTag('spiroski_domain_events.listener');

        parent::build($container); // TODO: Change the autogenerated stub
    }

}